### ISSUE TITLE
Add per world players

### ISSUE THREAD

**Issue by NaniITzJerry** [JackMD/ScoreHud-Addons#3]
Can You Set World Player Online ? Like World Plot Have 2 Player 
Plot : (playerinplotworld)

BADENGLISH

**Comment by JackMD** [comment]
This will be added to BasicAddon.php later

**Comment by JackMD** [comment]
Use `{world_player_count}` for showing that

**Comment by NaniITzJerry** [comment]
Na it perworld but i want people can see in world online not perworld example 
im at Lobby world 
but i can see Plot World How Many Player 
bad english

**Comment by JackMD** [comment]
Ask someone to make a custom scoreboard plugin for you. I am not doing it for you!
