### ISSUE TITLE
Add Pvplevels addon

### ISSUE THREAD

**Issue by SuperAdam47** [JackMD/ScoreHud-Addons#6]

**Comment by SuperAdam47** [comment]
https://github.com/corytortoise/PvPLevels

**Comment by SuperAdam47** [comment]
{killstreaks}

**Comment by JackMD** [comment]
# I won't be making any more addons. So if you would like a plugin to be supported then ask the author of that plugin to make a ScoreHud addon.


(Extract taken from the readme)
