### ISSUE TITLE
SKyblock add-on crashing 

### ISSUE THREAD

**Issue by jaylac2000** [JackMD/ScoreHud-Addons#7]
The skyblock add on is crashing my server not sure why

just a few days ago i started getting this issue

[Server thread/CRITICAL]: Error: "Call to undefined method room17\SkyBlock\session\Session::hasIsle()" (EXCEPTION) in "C:/Users/Administrator/Documents/mc servers/skyblock - hub/plugin_data/ScoreHud/addons/SkyBlockAddon" at line 48

**Comment by JackMD** [comment]
Please ask the author of the SkyBlock plugin to fix his addon

**Comment by jaylac2000** [comment]
will do because also /is accept gives internal server error. thanks
